### ISSUE TITLE
Issue in even_odd_site.cc

### ISSUE THREAD

**Issue by camk503** [Jamoeoe/openSource#7]
To reproduce: 
Syntax error, so run the program

Expected behavior:
Writes a line into the file

Actual behavior: 
Compiler error

Arrows the wrong way in line 18 ([file >> "..."] instead of [file << "..."]), should be writing into the file

**Comment by camk503** [comment]
To reproduce:
Syntax error, so run the program

Expected behavior:
Clears the buffer (I think?)

Actual behavior:
Compiler error

Missing semicolon in line 21

**Comment by camk503** [comment]
To reproduce:
Run the program

Expected behavior:
Prints out the correct even and odd numbers in the table

Actual behavior:
After 1, every number is odd

**Comment by Jamoeoe** [comment]
Issue 1, changed direction of arrows line 20
Issue 2, added semicolon to line 23
Issue 3, changed / operator to % line 13.
