### ISSUE TITLE
sum_even_fib.java

### ISSUE THREAD

**Issue by Jamoeoe** [Jamoeoe/openSource#8]
Doesn't output expected value

Steps to Reproduce
run code normally

Expected Behavior A clear and concise description of what you expected to happen.
Expected output of 4613732

Actual Behavior A clear and concise description of what actually happened.
Output is 4194305

Additional Information

Operating System: MacOS
Browser: Chrome
Version: 1.0
Any other relevant information
Possible Solution If you have any suggestions for a possible solution, please include them here.

Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? Low, medium, or high priority?
High

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always

Impact What is the impact of this issue/bug? Low, medium, or high?
High

**Comment by nichkent** [comment]
Fixed issue in line 4. b = 1 now

Fixed issue in line 5. sumEven = 0 now

Fixed issue in line 7. b % 2 == 0 now

Fixed issue in line 12. a = temp now
